### ISSUE TITLE
Exit code 1 due to uncommitted changes

### ISSUE THREAD

**Issue by rlgreen91** [whitesmith/rubycritic#277]
I'm running Rubycritic as part of a series of rake tasks within CodeClimate.  Ironically enough, I have a PR upgrading Rubycritic to the latest version.  However, CI keeps failing with the following error:

```
bundle exec rubycritic --minimum-score 85 --mode-ci --no-browser --path /tmp/artifacts/rubycritic app config lib
Uncommitted changes are present.
Exited with code 1
```

Has anyone seen this error before?  I'm trying to figure out where this is coming from, since all tracked files in the branch have been committed and running rubycritic locally completes successfully.  My Ruby version is 2.5

**Comment by Onumis** [comment]
Hmm, must have been introduced here: https://github.com/whitesmith/rubycritic/pull/271
:thinking:

**Comment by Onumis** [comment]
Reviewing the method `uncommitted_changes?`:

```ruby
      def self.uncommitted_changes?
        !`git ls-files --other --exclude-standard --directory`.empty? || !`git status --porcelain`.empty?
      end
```

I think we need to drop the `git ls-files` part, since it seems it will output folders like `tmp`, which are not tracked but might exist after running rubycritic, or simply loading a rails app.

`git status --porcelain` might be enough to tell if there are uncommitted changes, or even a `git diff-index HEAD --`

Will read on this and see what is best: https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes

**Comment by rlgreen91** [comment]
I wanted to come back around and explain what exactly the issue was for us.  So, we encountered this issue running Rubycritic on CircleCI.  The thing about CircleCI and other CI services is that we don't have any of the gems installed - it has to do that.  As part of that build script, we would create a `/vendor` directory that CircleCI would install the gems in.  Rubycritic would then complain about uncommitted changes, which occurred because that directory literally didn't exist until CircleCI started running.  So that was our issue.  Adding `/vendor` to our .gitignore solved it for now.

**Comment by Onumis** [comment]
Thanks for the info! Anyway, the fix I proposed is still a better way of detecting such things.
