### ISSUE TITLE
Allow configuring date range of Churn calculation

### ISSUE THREAD

**Issue by natesholland** [whitesmith/rubycritic#37]
I'm running rubycritic on a large project that's been running for 10 years so our git log is very long. I'm thinking we should limit it by commits within the last year in order to speed things up. My calculations showed that this would speed up the churn section by 500% on older projects.

**Comment by bglusman** [comment]
Relatedly @guilhermesimoes, I was just trying to upgrade debt_ceiling to the new 1.4 version so I can avoid using the rubycritic internals the way you showed me a few months back, but it's WAY slower now, even in :ci mode, which I beleive skips the churn analysis, correct?  I'd like to use your latest, but I may have to roll back to old version unless there's some undocumented way I'm missing to get the speed I was getting in [this code](https://github.com/bglusman/debt_ceiling/blob/v0.1.1/lib/debt_ceiling/accounting.rb#L39)

**Comment by guilhermesimoes** [comment]
@bglusman `--mode-ci` does not skip churn calculation, since we need it to generate that "Complexity vs Churn" scatter plot. That mode simply makes sure that RubyCritic runs once instead of twice.

The things is, using the new API, you're running [all these analysers](https://github.com/whitesmith/rubycritic/blob/4219403a524db249ebd18d00ba8e836e9f486b5f/lib/rubycritic/analysers_runner.rb#L14-L19). So obviously it will be slower than just the two you were using previously. I'll have to work on something to let you pick which analysers to run...

**Comment by bglusman** [comment]
@guilhermesimoes hmm, OK, that makes sense...  after some changes I'm actually using most of all of these analyzers now, EXCEPT for churn, so being able to turn that off (which I thought we discussed specifically for ci mode in November) would be great, but yeah, making it a more general feature to specify which makes sense.  I suppose since I'm using most of them now I could leave it as is, or go back to semi-manual/hacky user of your internal API until that's done.  I could probably do a PR to make that change myself this week if you'd like, or let me know if you prefer to do yourself?
