### ISSUE TITLE
Comparison mode runs twice when in default branch

### ISSUE THREAD

**Issue by denny** [whitesmith/rubycritic#377]
If you set a branch for comparisons, then run rubycritic while that branch is checked out, it runs against the same branch twice - which seems like wasted effort, unless I'm missing something.

I've added this as a separate issue from #287 because it's not about the file layout, but I'm tag-linking them in case somebody wants to tackle both at once 🙂

**Comment by rishijain** [comment]
Yes, I imagine there is no logical need to compare same branches at all and it is most likely a mistake from the user. So may be it would be better to raise an error instead of running it once for the branch or continue running twice like it is now.  I have created the above PR based on that it should raise a Runtime error rather than silently handling it.

**Comment by etagwerker** [comment]
I believe this was fixed by #471
