### ISSUE TITLE
What heppend to my code?

### ISSUE THREAD

**Issue by xdougx** [whitesmith/rubycritic#41]
All my code has been lost when i use this gem? 5 days of code and test just get lost!
what hell this gem do when I run?

**Comment by guilhermesimoes** [comment]
Hmm, did you cancel RubyCritic while it was running?

Could you check your git stash? `git stash show -p stash@{0}`

**Comment by xdougx** [comment]
![screen shot 2015-03-20 at 2 37 01 pm](https://cloud.githubusercontent.com/assets/1920415/6757276/9d7c8dee-cf0e-11e4-8d20-cd728866abaf.png)

**Comment by xdougx** [comment]
i didnt stop, it just get a exception and stop running

**Comment by xdougx** [comment]
63 files changed, 596 insertions(+), 1201 deletions(-)

**Comment by xdougx** [comment]
How can i get it back?

**Comment by guilhermesimoes** [comment]
Try `git stash apply`.

**Comment by xdougx** [comment]
Fine, its work, all my files get back to theirs places, but what really happens when i run rubycritic

**Comment by guilhermesimoes** [comment]
RubyCritic analysis your code twice. First, it analyses your code as is. Then, it uses Git to go your last commit and analyses that code as well. This way, it can compare your before and after code and determine if you are introducing new code smells. Finally, if everything works correctly, it uses Git to go back to your original code.

Unfortunately, something broke which prevented RubyCritic from using Git to go back to your original code. However, you did not provide any information about what went wrong so I'm afraid I can't help you any further. Luckily your code was stashed but let this serve you as a warning. Commit often

**Comment by brandondrew** [comment]
In order to guard against alarming users in cases where there's an interruption between reverting to the previous commit and moving ahead to the current code, perhaps it might be a good idea to add a file to the working directory named (in shouting caps) "HOW_TO_RETREIVE_YOUR_LOST_CODE.md" (or something like that).  It could be automatically removed as soon as the code was back to normal, so it would only be seen in cases like this.  

I imagine it is quite alarming to see something like this happen.

**Comment by xdougx** [comment]
+1
