### ISSUE TITLE
Is this normal? 

### ISSUE THREAD

**Issue by xdougx** [whitesmith/rubycritic#43]
![screen shot 2015-03-23 at 10 18 54 am](https://cloud.githubusercontent.com/assets/1920415/6780676/1eb610ae-d146-11e4-9877-6e9dfb67d170.png)

Im using ruby singleton class but, i got this error, is this normal?

**Comment by guilhermesimoes** [comment]
Yes, that's normal. In fact, if you run RubyCritic over RubyCritic, you'll find a couple of those issues. That issue is not without its merits, but I've thought about turning it off a few times :)

You can turn it off by creating a `.reek` file with the following configuration:

```yaml
---
FeatureEnvy:
  enabled: false
```

Or by adding a special comment before that method. For more information, check [Reek's wiki](https://github.com/troessner/reek/wiki/Smell-Suppression).
