### ISSUE TITLE
Incomplete constant name if file has no methods

### ISSUE THREAD

**Issue by jbodah** [whitesmith/rubycritic#59]
Given

```rb
module Office365
  # This class represents the cached user information retrieved from the
  # ActiveDirectory Graph API. It is a user that exists within a Microsoft
  # Azure Active Directory. It is used for user management.
  class User < ActiveRecord::Base
  # ...
```

Instead of showing up as `Office365::User` it simply shows up as `User` (which also shows up for `app/models/user.rb`)

<img width="796" alt="rubycritic" src="https://cloud.githubusercontent.com/assets/6093002/8842649/c1d9f532-30ca-11e5-8891-69802870d101.png">

**Comment by troessner** [comment]
Actually I'd consider this a bug. Re-labeled. Let's fix this.

**Comment by Onumis** [comment]
This is currently a feature: [when a file has no methods, returns the name of the file titleized](https://github.com/whitesmith/rubycritic/blob/master/test/lib/rubycritic/analysers/helpers/modules_locator_test.rb#L41)

I don't mind having this changed to include the module name (if it exists) for classes without methods.

The conditions to having the name of the file displayed instead of the "qualified name" are:

- file is empty
- file is unparsable
- file has no methods

**Comment by troessner** [comment]
I'd prefer to have the module name always included as well.

**Comment by troessner** [comment]
#96 has been merged -> closed!
