### ISSUE TITLE
Break on Continuous Integration based on a threshold

### ISSUE THREAD

**Issue by RobertoSchneiders** [whitesmith/rubycritic#98]
We are migrating our code analisys from code climate (which is awesome) to open source tools and we are using rubycritic (also awesome). 

We want to break the build on CI if the quality is bellow a threshold. Unfortunately I can't do this easily with rubycritic. I had to create a pretty crazy shell [script](https://gist.github.com/RobertoSchneiders/f8b319440accf3ad4da5). 

I'm wondering if you guys think this could be implemented inside rubycritic, what do you think?

I found this gem [quality-control](https://github.com/gdotdesign/quality-control) which basicaly do exactly that (they also have rating threshold, which sounds good), but, I'm trying to avoid this dependency. (The project don't seems to be very active)

**Comment by troessner** [comment]
Yes, I would **love** this functionality. 
WDYT about a cli switch like "--minimum-score" based on [our current scoring](https://github.com/whitesmith/rubycritic/pull/35)?

**Comment by RobertoSchneiders** [comment]
@troessner pretty much what I had in mind. :+1:

**Comment by RobertoSchneiders** [comment]
Any insights on how we can do this?

**Comment by troessner** [comment]
[1] Add the cli option to our [options](https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/cli/options.rb)
[2] Check the calculated [score](https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/core/analysed_modules_collection.rb#L32)
[3] Then change our [generators](https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/generators/json/simple.rb)

Implementing this is pretty easy. Doing this "the right away" without making our overall architecture is not.
[1] and [2] is straightforward, [3] not:

* AFAIS right now our reporters / generators have no notion of setting a proper exit status (so they just use the default)
* Additionally to that you'd need to "carry" this configuration setting through in a clean extensible way from beginning to the end (because it's the first thing RubyCritic gets handed and the last thing it needs to evaluate)

Would you like to take a stab at this?
I'd help you with constant reviews on a preliminary pull request ;)

**Comment by RobertoSchneiders** [comment]
Great! Yeah, I will try. I think I have some time on friday.

**Comment by RobertoSchneiders** [comment]
Released on `2.6.0`.
